### PR TITLE
I added my name, small info about me and a picture of my dog.

### PR DESCRIPTION
**Pull request by paogomco**
Edited the read me to add my name, however, I don't know if I did the header, list,  and picture in the correct way. I saw some youtube videos and read about R markdown but don't know if I did that part correctly.

### CODE REVIEW

**Review by rkcatipon — COMMENTED** [review]
Hi Paolo! Looking at your pull comments, it looks like you might have not have pushed the latest version with the picture of your pupper. From what I see in the code, here is the feedback:
For next time:
- Maybe check if you need to save and push one more time to render the changes you made.
- Perhaps add more markdown elements like bolding text and adding a list
- More headers too

A few wins:
- You do have a good example of a H1 header
- Included some background info on  who you are and what you're studying
- You successfully pushed your content, and submitted a pull request

**Comment by deblnia** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |             |       X     |
| **Coding strategy**         |           |     X        |            |
| **Presentation**            |           |            |       X       |
| **Achievement, creativity** |           |       X       |            |
| **Reproducibility**         |           |             |  X          |

Remarks:

* Hi Paolo! Echoing Rachel, I don't think you pushed that commit with your name, the info about you and your dog pic. It's really important that you get this for future homeworks so I'd suggest taking another look at the [homework workflow](https://cfss.uchicago.edu/homework/edit-readme/), specifically the video.  
* If you still need help, I'd be happy to work through the submission process in office hours. I'm grading right now based on what your commit message says you've done, and your partial use of git.

**Comment by tyin29** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |     X          |            |
| **Coding strategy**         |           |     X          |            |
| **Presentation**            |           |              |      X       |
| **Achievement, creativity** |           |              |  X          |
| **Reproducibility**         |           |              |      X       |

Hi Paola,

You did a good job by changing the file with a brief introduction of yourself and pushed it to GitHub, but there are also some aspects that you may want to improve on. Below are my specific comments.

Three aspects you did well:
1. You successfully pulled from GitHub and pushed the commit to GitHub for review, which means that you have mastered the techniques taught in the first week.
2. You mentioned in the commit message that you added your name, info, and a picture, which means that you have known what to do with the message box in R when you make a commit to local change.
3. The header markdown is done in the correct way.

Three aspects you may need to improve on:
1. Including more elements with different syntaxes, such as emphasis and list, will make the file look better.
2. You mentioned that you added your name, info, and a picture of your dog, but the file pushed only shows your name. You may want to refer to this website for styling different forms of writing.
3. Maybe you can include more about yourself.

**Review by tyin29 — COMMENTED** [review]
Hi Paola,

You did a good job by changing the file with a brief introduction of yourself and pushed it to GitHub, but there are also some aspects that you may want to improve on. Below are my specific comments.

Three aspects you did well:
1. You successfully pulled from GitHub and pushed the commit to GitHub for review, which means that you have mastered the techniques taught in the first week.
2. You mentioned in the commit message that you added your name, info, and a picture, which means that you have known what to do with the message box in R when you make a commit to local change.
3. The header markdown is done in the correct way.

Three aspects you may need to improve on:
1. Including more elements with different syntaxes, such as emphasis and list, will make the file look better.
2. You mentioned that you added your name, info, and a picture of your dog, but the file pushed only shows your name. You may want to refer to this website for styling different forms of writing.
3. Maybe you can include more about yourself.

**Pull request closed without merging**
